# Generated by Django 3.0.5 on 2020-11-30 16:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50)),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
