# Generated by Django 3.0.5 on 2020-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('thumbnail', models.URLField()),
                ('city', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000, verbose_name='Información del item')),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=5)),
                ('rating', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['id'],
            },
        ),
    ]
